/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDocker: typeof import('./../components/BaseDocker.vue')['default']
    BaseHeader: typeof import('./../components/BaseHeader.vue')['default']
    CesiumMap: typeof import('./../components/CesiumMap.vue')['default']
    CreateEntityPop: typeof import('./../components/PopUp/createEntityPop.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GenLinkPop: typeof import('./../components/PopUp/genLinkPop.vue')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    PopUp: typeof import('./../components/PopUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WarPlanPop: typeof import('./../components/PopUp/warPlanPop.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
