/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDocker: typeof import('./../components/BaseDocker.vue')['default']
    BaseHeader: typeof import('./../components/BaseHeader.vue')['default']
    CesiumMap: typeof import('./../components/CesiumMap.vue')['default']
    CreateEntityPop: typeof import('./../components/PopUp/createEntityPop.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    GenLinkPop: typeof import('./../components/PopUp/genLinkPop.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDataAnalysis: typeof import('~icons/ep/data-analysis')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpPieChart: typeof import('~icons/ep/pie-chart')['default']
    IEpPointer: typeof import('~icons/ep/pointer')['default']
    IEpRefreshRight: typeof import('~icons/ep/refresh-right')['default']
    IEpTickets: typeof import('~icons/ep/tickets')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpVideoPause: typeof import('~icons/ep/video-pause')['default']
    IEpVideoPlay: typeof import('~icons/ep/video-play')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    PopUp: typeof import('./../components/PopUp.vue')['default']
    ReplayChartGant: typeof import('./../components/PopUp/replayChartGant.vue')['default']
    ReplayChartLine: typeof import('./../components/PopUp/replayChartLine.vue')['default']
    ReplayChartPop: (typeof import('../components/PopUp/replayChartGant.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveThoughtPop: typeof import('./../components/PopUp/saveThoughtPop.vue')['default']
    ToolTip: typeof import('./../components/ToolTip.vue')['default']
    WarPlanPop: typeof import('./../components/PopUp/warPlanPop.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
